// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1FEV1vS-uiPIkQU-GWkxkwqHam1c-pg',
    appId: '1:898375381108:web:a88091387edba88802e121',
    messagingSenderId: '898375381108',
    projectId: 'crazyapps-e71d4',
    authDomain: 'crazyapps-e71d4.firebaseapp.com',
    databaseURL: 'https://crazyapps-e71d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crazyapps-e71d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0p9PGQb3jDZH0iaj-8U76oVXpkWF3oGk',
    appId: '1:898375381108:android:fb700dd67cb9d3f802e121',
    messagingSenderId: '898375381108',
    projectId: 'crazyapps-e71d4',
    databaseURL: 'https://crazyapps-e71d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crazyapps-e71d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2enAc4S7CzjXW4HNZonOPGpTj1QL-DMA',
    appId: '1:898375381108:ios:24e69b11c3f5e3c002e121',
    messagingSenderId: '898375381108',
    projectId: 'crazyapps-e71d4',
    databaseURL: 'https://crazyapps-e71d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crazyapps-e71d4.appspot.com',
    iosClientId: '898375381108-ok4otnbfd00kvrhn3gn1h24nmo9snntv.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2enAc4S7CzjXW4HNZonOPGpTj1QL-DMA',
    appId: '1:898375381108:ios:47145e5c0896fc8d02e121',
    messagingSenderId: '898375381108',
    projectId: 'crazyapps-e71d4',
    databaseURL: 'https://crazyapps-e71d4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crazyapps-e71d4.appspot.com',
    iosClientId: '898375381108-du8qe9oasteag5knljtnb73057suhgo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyapps.RunnerTests',
  );
}
